### ISSUE TITLE
rosbag file?

### ISSUE THREAD

**Issue by ljjTYJR** [PRBonn/SIMP#1]
Hi, do you have some ros bag files to play with the demo?

**Comment by FullMetalNicky** [comment]
Hi! 
I will have to ask Prof. Stachniss...we are planning to publish a dataset paper with the recordings we made, so I am not sure he will approve releasing a part of it before we even submit the paper.

**Comment by FullMetalNicky** [comment]
@ljjTYJR Hi Again!
I added a 60-second ROS bag (ROS1) that can be downloaded with the corresponding ground truth - it's at the last section called Demo. 

You can use it to run both the mapping and the localization. 
This isn't a recording we used in the evaluation, just a random one I found on my computer that we don't intend to publish for the dataset. So you should be able to make our algo run but the performance may vary.

**Comment by ljjTYJR** [comment]
@FullMetalNicky Hi, thanks for your reply, I have successfully run the nice demo.

One minor question: when mapping, are you using the `gt` odom information?

**Comment by FullMetalNicky** [comment]
@ljjTYJR Yes, I am using the GT information from the ground truth csv file, that was extracted from the AprilTags, so it's very precise. We also have a pose file that is extracted through ICP - we show the results in the paper, and they are nearly identical. 

You can try to use a tracking camera (e.g. realsense T265)  for the poses. You will need to give it an initial pose that corresponds to the floor plan though - I implemented something like that using the "clicked point" topic in RVIZ. So I clicked on the RVIZ map to mark where the robot starts from, and then updated the pose in the global (floor plan) frame using the visual odometry. I didn't test it very thoroughly because that would mean implementing an actual SLAM system, and I was aiming for mapping with known poses...

**Comment by ljjTYJR** [comment]
@FullMetalNicky Thanks for the reply.

One more simple question:
Are there some good ways to deal with "Re-Identification" during mapping?
For example, from the image input, the robot can detect the objects and get the 3d bounding box. 
Then the robot turns around and loses the detection, after a while, the robot returns to the previous location, how can the robot make correct data-association?

**Comment by FullMetalNicky** [comment]
@ljjTYJR Yes. I'm handling re-identification in SIMP.py. There are some methods for merging objects in that file. 
If objects are of the same class, have some IoU between their bounding boxes or their centers are "statistically close enough", I am merging them into a single object. 
However, if your pose estimation is not good, and the object is detected again at some distance from the previous detection, it's a problem. Because you can't know if you detect another instance of the same class (e.g. 2 tables standing next to each other) or you just have a wrong pose for the same object.

**Comment by ljjTYJR** [comment]
Thank you @FullMetalNicky , :)
